version: '2.3'
services:
  notebook:
    build: .
    env_file: .env
    ports:
      - "5003:8888"
    volumes:
      - ../data:/data
      #- /mnt/qb/data:/data
      - /tmp:/tmp
      - .:/src/nnfabrik
      - ./notebooks:/notebooks
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=0
